### ISSUE TITLE
Cron job generation fails

### ISSUE THREAD

**Issue by eythian** [mcuhq/SphinxSearchPlugin#19]
When running through the wizard, I enter the details for cron, and it gives me a blank screen with this in the logs:

    PHP Fatal error:  Call to protected method Gdn_Validation::AddValidationField() from context 'SphinxSearchPlugin' in /var/www/xyz/vanilla/plugins/SphinxSearch/class.sphinxsearch.plugin.php on line 350

According to this:
https://vanillaforums.org/discussion/30699/howto-install-sphinx-search-on-ubuntu-14-04
it should be putting them in a non-writeable directory (which seems problematic), but even making it writeable doesn't help.

**Comment by mcuhq** [comment]
Which version of vanilla are you running?

**Comment by pvanhemmen** [comment]
Same issue here.

Latest version of Vanilla 2.2.1
php 5.6
SphinxSearch 2.0.4

**Comment by mcuhq** [comment]
@pvanhemmen Yep, it looks like a vanilla upgrade changed the signature of `addValidationField`. Commenting out those lines will work, but will no longer protect against empty paths.
