### ISSUE TITLE
Vanilla Forum Sphinx install problem

### ISSUE THREAD

**Issue by GiacomoSilli** [mcuhq/SphinxSearchPlugin#21]
I'm following the guide, i'm stuck on step 8 (https://open.vanillaforums.com/addon/sphinxsearch-plugin)
I have downloaded the .deb package not the Source tarball (tar.gz)
I'm on ubuntu 16.04 x64

Do you know whats the problem?

I have the following error:
```

root@vps****:~# /usr/bin/indexer --all --config /etc/sphinxsearch/sphinx.conf
Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
using config file '/etc/sphinxsearch/sphinx.conf'...
indexing index 'test1'...
ERROR: index 'test1': sql_query: Table 'vanilla5.documents' doesn't exist (DSN=mysql://root:***@localhost:3306/vanilla5).
total 0 docs, 0 bytes
total 0.002 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'test1stemmed'...
ERROR: index 'test1stemmed': sql_query: Table 'vanilla5.documents' doesn't exist (DSN=mysql://root:***@localhost:3306/vanilla5).
total 0 docs, 0 bytes
total 0.000 sec, 0 bytes/sec, 0.00 docs/sec
skipping non-plain index 'dist1'...
skipping non-plain index 'rt'...
total 0 reads, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg
total 0 writes, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg
```

**Comment by mcuhq** [comment]
IT doesn't look sphinx can find the correct table - in fact I don't think `documents` is even a table it should be looking for. See if you can follow this guide here for Ubuntu: https://open.vanillaforums.com/discussion/30699/howto-install-sphinx-search-on-ubuntu-14-04

**Comment by GiacomoSilli** [comment]
I think it's a bug of the standard download from the vanilla site,
I installed the new version downloaded from here and it seems to work properly.

I have another question, the procedure for the cron seems to have worked properly,
How often the db is updated?
I created new threads and post a few hours ago, is still not appearing in the search

**Comment by mcuhq** [comment]
On default, it creates a cron template to run every 2 hours. You can change this by editing the `cron.reindex.delta.php.tpl` in your `assets` folder in the plugin directory.

**Comment by GiacomoSilli** [comment]
This is my cron.reindex.delta.php:
```
define('PATH_TO_SPHINX_INDEXER', '/usr/bin/indexer');
define('PATH_TO_SPHINX_CONFIG', '/etc/sphinxsearch/sphinx.conf');
define('SPHINX_INDEX_NAME', 'vss_');

$Command = PATH_TO_SPHINX_INDEXER." --config ".PATH_TO_SPHINX_CONFIG." ".SPHINX_INDEX_NAME."delta --rotate >> /var/www/html/vanilla/plugins/SphinxSearch/cron/sphinx_cron.log 2>&1";
exec($Command);
```
This is my cron.reindex.delta.php.tpl:
```
<?php

/*
 * Add the following cron job to update the delta index every 2 hours
 */
// 0 */2 * * * {path_to_php} {path_to_cron}{DS}cron.reindex.delta.php

define('PATH_TO_SPHINX_INDEXER', '{path_to_indexer}');
define('PATH_TO_SPHINX_CONFIG', '{path_to_config}');
define('SPHINX_INDEX_NAME', '{index_prefix}');

$Command = PATH_TO_SPHINX_INDEXER." --config ".PATH_TO_SPHINX_CONFIG." ".SPHINX_INDEX_NAME."delta --rotate >> {path_to_cron}{DS}sphinx_cron.log 2>&1";
exec($Command);
```
But it doesnt work, no update up there

**Comment by mcuhq** [comment]
Did you add this to your crontab? Run `crontab -e` and add the commented out line inside there found in `cron.reindex.delta.php`

**Comment by GiacomoSilli** [comment]
Yes, I added the line commented
 `"0 * / 2 * * * / usr / bin / php /var/www/html/vanilla5/plugins/SphinxSearch/cron/cron.reindex.delta.php"`
But it did not work.

I have now added this:
`/ usr / bin / indexer --config /etc/sphinxsearch/sphinx.conf vss_delta --rotate >> /var/www/html/vanilla5/plugins/SphinxSearch/cron/sphinx_cron.log 2> & 1`

It seems to work.
I have a memory problem, the folder ../sphinxsearch/data takes a lot memory.
Can i edit binglog_path in /etc/sphinxsearch/sphinx.conf file to  binlog_path = # to disable logs or it could create problems?

**Comment by mcuhq** [comment]
You may need to make sure that the cron file is executable by using `chmod`. The paths must be correct if you do it manually, so something is going amiss with crontab. 

Not sure about the repercussions of not using logs with sphinx, but I'd guess it wouldn't affect the indexing and normal operation.

**Comment by GiacomoSilli** [comment]
Seem to work now with the line found in cron.reindex.delta.php

But seems to wont work if i remove 
```
    path            = /var/lib/sphinxsearch/data/vss_main
    path            = /var/lib/sphinxsearch/data/vss_delta
```

Unfortunately they take up too much space

**Comment by mcuhq** [comment]
Yep, those paths are mandatory. @see http://sphinxsearch.com/docs/current.html#conf-path

**Comment by GiacomoSilli** [comment]
If I allocate more space to sphinx, this will be occupied indefinitely or has a limit? or do I have to delete the files in data folder manually?

**Comment by mcuhq** [comment]
It has a limit which is directly proportional to how many records you are indexing. Sphinx will create an optimized index file to quickly lookup the corresponding UUID that matches your vanilla forum's row ID number. Don't delete any files generated by sphinx in there. First allocate a bunch of memory and note its size. Then one week later note its size again and you should be able to extrapolate the expected size over time due to your site's traffic.

**Comment by GiacomoSilli** [comment]
Unfortunately I'm using a test server, not much space I have, indeed, I have little, about 8gb free.
My forum has thousands of registered users and about 200 active simultaneously.
Surely occupy more than 8GB, I will have to stop using the plugin or manually delete files in the folder and hoping nothing happens, until the moment when I will change the server

Thanks for your help

**Comment by mcuhq** [comment]
You will need more space to continue. You can also ask on the sphinx forums.
